from typing import Any, List, Dict, Callable
from talkingtomachines.generative.prompt import (
    generate_conversational_system_message,
    generate_demographic_prompt,
)
from talkingtomachines.generative.llm import query_llm

DemographicInfo = dict[str, Any]


class SyntheticAgent:
    """A class for constructing the base synthetic agent.

    Args:
        experiment_id (str): The ID of the experiment.
        experiment_context (str): The context of the experiment.
        session_id (str): The ID of the session.
        demographic_info (DemographicInfo): The demographic information of the user.
        model_info (str): The information about the model used by the agent.
        demographic_prompt_generator (Callable[[DemographicInfo], str], optional):
            A function that generates a demographic prompt based on the demographic information.
            Defaults to generate_demographic_prompt.

    Attributes:
        experiment_id (str): The ID of the experiment.
        experiment_context (str): The context of the experiment.
        session_id (str): The ID of the session.
        demographic_info (DemographicInfo): The demographic information of the user.
        model_info (str): The information about the model used by the agent.
    """

    def __init__(
        self,
        experiment_id: str,
        experiment_context: str,
        session_id: str,
        demographic_info: DemographicInfo,
        model_info: str,
        demographic_prompt_generator: Callable[
            [DemographicInfo], str
        ] = generate_demographic_prompt,
    ):
        self.experiment_id = experiment_id
        self.experiment_context = experiment_context
        self.session_id = session_id
        self.demographic_info = demographic_prompt_generator(demographic_info)
        self.model_info = model_info

    def get_experiment_id(self) -> str:
        """Return the experiment ID of the synthetic agent.

        Returns:
            str: The experiment ID of the synthetic agent.
        """
        return self.experiment_id

    def get_session_id(self) -> str:
        """Return the session ID of the experiment.

        Returns:
            str: The session ID of the experiment.
        """
        return self.experiment_id

    def get_experiment_context(self) -> str:
        """Return the experiment context of the synthetic agent.

        Returns:
            str: The experiment context of the synthetic agent.
        """
        return self.experiment_context

    def get_demographic_info(self) -> str:
        """Return the demographic information of the synthetic agent.

        Returns:
            str: The demographic information of the synthetic agent
        """
        return self.demographic_info

    def get_model_info(self) -> str:
        """Return the model information of the synthetic agent.

        Returns:
            str: The model information of the synthetic agent
        """
        return self.model_info

    def respond(self, question: str) -> str:
        """Generate a response based on the synthetic agent's model.

        Args:
            question (str): A question or prompt to which the agent should respond.

        Returns:
            str: The response generated by the synthetic agent
        """
        try:
            return ""
        except Exception as e:
            # Log the exception
            print(f"Error during response generation in SyntheticAgent object: {e}")
            return None


class ConversationalSyntheticAgent(SyntheticAgent):
    """A synthetic agent that interacts with users in a conversational system. Inherits from the SyntheticAgent base class.

    Args:
        experiment_id (str): The ID of the experiment.
        experiment_context (str): The context of the experiment.
        session_id (str): The ID of the session.
        demographic_info (DemographicInfo): The demographic information of the user.
        model_info (str): The information about the model used by the agent.
        assigned_treatment (str): The assigned treatment for the user.
        demographic_prompt_generator (Callable[[DemographicInfo], str], optional):
            A function that generates a demographic prompt based on the demographic information.
            Defaults to generate_demographic_prompt.

    Attributes:
        assigned_treatment (str): The assigned treatment for the synthetic agent.
        system_message (str): The system message generated for the conversation.
        message_history (List[dict]): The history of the conversation with the synthetic agent.
    """

    def __init__(
        self,
        experiment_id: str,
        experiment_context: str,
        session_id: str,
        demographic_info: DemographicInfo,
        role: str,
        model_info: str,
        treatment: str,
        demographic_prompt_generator: Callable[
            [DemographicInfo], str
        ] = generate_demographic_prompt,
    ):
        super().__init__(
            experiment_id,
            experiment_context,
            session_id,
            demographic_info,
            model_info,
            demographic_prompt_generator,
        )
        self.role = role
        self.treatment = treatment
        self.system_message = generate_conversational_system_message(
            experiment_context=self.experiment_context,
            role=self.role,
            treatment=self.treatment,
            demographic_info=self.demographic_info,
        )
        self.message_history = [
            {"role": "system", "content": self.get_system_message()},
        ]

    def get_assigned_treatment(self) -> str:
        """Return the assigned treatment of the synthetic agent.

        Returns:
            str: The assigned treatment of the synthetic agent.
        """
        return self.assigned_treatment

    def get_system_message(self) -> str:
        """Return the system message of the synthetic agent.

        Returns:
            str: The system message of the synthetic agent.
        """
        return self.system_message

    def get_message_history(self) -> List[dict]:
        """Return the message history of the synthetic agent.

        Returns:
            List[dict]: The conversation history of the synthetic agent
        """
        return self.message_history

    def update_message_history(self, message: str, message_type: str) -> None:
        """Update the message history of the synthetic agent with a new message.

        Args:
            message (str): A message to add to the conversation history.
            message_type (str): Either user or assistant.

        Returns:
            None
        """
        if message_type == "user":
            self.message_history.append({"role": "user", "content": message})
        elif message_type == "assistant":
            self.message_history.append({"role": "assistant", "content": message})
        else:
            # Log the exception
            print(
                f"Message type {message_type} is not supported. Need to use either user or assistant."
            )
            return None

    def respond(self, question: str) -> str:
        """Generate a response to a question posed to the synthetic agent.

        Args:
            question (str): A question or prompt to which the agent should respond.

        Returns:
            str: The response generated by the synthetic agent.
        """
        try:
            self.update_message_history(message=question, message_type="user")
            response = query_llm(
                model_info=self.get_model_info, message_history=self.get_message_history
            )
            self.update_message_history(message=response, message_type="assistant")
            return response

        except Exception as e:
            # Log the exception
            print(
                f"Error during response generation by ConversationalSyntheticAgent object: {e}"
            )
            return ""
